//INNER JOIN
SELECT A.ID, A.NAME, A.KNAME
    FROM A INNER JOIN B
        ON A.ID = B.ID;

//LEFT JOIN
SELECT A.ID, A.NAME, A.KNAME
    FROM A LEFT OUTER JOIN B
        ON A.ID = B.ID;

//LEFT JOIN 중 왼쪽에 있는것만
SELECT A.ID,A.NAME,A.KNAME
    FROM A LEFT OUTER JOIN B
        ON A.ID = B.ID
    WHERE B.ID IS NULL;

//RIGHT JOIN
SELECT A.ID,A.NAME,A,KNAME
    FROM A RIGHT OUTER JOIN B
        ON A.ID = B.ID;

//RIGHT JOIN 중 오른쪽에 있는 것만
SELECT A.ID, A.NAME, A.KNAME
    FROM A RIGHT OUTER JOIN B
        ON A.ID = B.ID
    WHERE A.ID IS NULL;

//OUTER JOIN
SELECT A.ID, A.NAME, A.KNAME
    FROM A LEFT JOIN B
            ON A.ID = B.ID
    UNION
SELECT A.ID, A.NAME, A.KNAME
    FROM A RIGHT JOIN B
            ON A.ID = B.ID;


//오른쪽과 왼쪽만 겹치는 부분 X
SELECT A.ID, A.NAME, A.KNAME
    FROM A LEFT JOIN B
    UNION
SELECT A.ID, A.NAME, A.KNAME
    FROM A RIGHT JOIN B
             ON A.ID = B.ID
WHERE A.ID IS NULL OR B.ID IS NULL;
